Mouve Breadcrumb Outside of Layout
marmelab/ra-enterprise-demo pull request #93
Opened 2021-03-26 13:58 UTC by djhi

[Trello Card #335](https://trello.com/c/kqwA1oGv/335) 

## Release process

- [x] Select a Github label (**WIP** or **RFR**)

2021-03-30 13:18 UTC, fzaninotto requested changes
Waiting for a change in ra-enterprise that should remove the need for a custom BreadcrumbForAction

2021-03-30 13:18 UTC, fzaninotto commented
https://trello.com/c/XpAzDmqP/433-breadcrumbforaction-replace-by-variant-to-avoid-code-duplication

2021-04-20 13:19 UTC, djhi commented
Migrated to latest ra-navigation and ra-enterprise. Removed BreadcrumbForAction in favor of Breadcrumb with variant

2021-04-20 14:15 UTC, HALLERPierre approved these changes

2021-04-20 15:52 UTC, fzaninotto commented on src/invoices/InvoiceList.tsx
> +    useDefineAppLocation('sales.invoices');
why can't you set that in the InvoiceList? Because the underlying List component overrides it? If so, this will be counterintuitive for our users...

2021-04-20 15:54 UTC, fzaninotto commented on src/layout/Breadcrumb.tsx
> +        width: 'min-content',
I didn't know this value, would you mind adding a comment explaining why you need it?

2021-04-21 14:22 UTC, HALLERPierre approved these changes

2021-04-21 14:23 UTC, merged